# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:
  - jekyll-paginate
  - jemoji
permalink:        pretty

# Setup
title:            Yuliana Apaza
# tagline:          'My projects'
description:      "I'm  fresh graduate of National University of Saint Augustine (Arequipa, Perú)"
url:              "https://yuliana.me"
#url:              "localhost:4000"
baseurl:          /
paginate_path:    "blog/page:num/"
paginate:         5

author:
  name:           'Yuliana Apaza'
  email:          'yuliana.apaza94@gmail.com'
  twitter:        'https://twitter.com/yg_pon'
  github:         'https://github.com/yg-apaza'

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
